name: docs
on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - run: flit install .[docs]
    - name: Running the Sphinx to gh-pages Action
      uses: uibcdf/action-sphinx-docs-to-gh-pages@v1.0-beta.2
      with:
        branch: main
        dir_docs: docs
        sphinxopts: ''
